services:
  - type: web
    name: save-restricted-content-bot
    env: docker
    repo: https://github.com/yassuhacks750/SaveRestrictedContentBot
    branch: main  # या जो भी तुम्हारी default branch है (जैसे master)
    dockerfilePath: Dockerfile

    envVars:
      - key: API_ID
        value: "22849789"            # ← अपना Telegram API ID डालो
      - key: API_HASH
        value: "0fc127c6055acd59f00ec6c229e1e3c4"     # ← अपना Telegram API HASH डालो
      - key: BOT_TOKEN
        value: "7216195350:AAFVQ0SjLEC04vZvKEebkThJvewBxT9k4Ls"    # ← BotFather से मिला token
      - key: SESSION
        value: "1BVtsOHgBu0hALOMEsWQYf3wRq18kMxvt1ieMD5GQjzC5rvXOHo7xiz6uq6JMO2hfm8oeTpFqD6rCdVnDw4O9hQpKX8nG8ShGlje-orIf8qUEVZ2iQGVu55xTRqLkwCoPQVFCpyAE90tK7XYAPTCt9ETWROw_FiQr7x7azXfMUJ9Psfi_SI3yoejwUHIkTjDmufEUlgB78cdjA5HYMZrtOpK3xyDPJJbUWWRv77UsYab0kAjMMu52vx_j22Maxs91RxjMcALeQvTl6ssN5iYvXAP9FQFVLGMYC-gJnlznMKyprkGKobjp2pyP84FtzmgdeohspeERTExMF7cEI0Zt3BO4C6K5NbE="  # ← अभी generate किया हुआ session string
